---
main_app_name: greenfield
database_host: database
ruby_version: '2.7'
frontend_service: frontend
webserver_service: nginx
database_service: database
database_vendor: mysql
mysql_env_vars:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_PASSWORD: root
  MYSQL_USERNAME: root
  MYSQL_DATABASE_PORT: '3306'
thor_actions: 
  insert_hfci_gem_into_gemfile: y
