version: '3.2'

services:

  ruby_gem:
    image: roar
    build:
      context: .
      dockerfile: mise/containers/frontend/Dockerfile
    volumes:
      - .:/usr/src
      - .:/usr/app

    environment:
      - RUBY_VERSION='2.5'


volumes:
  gem_cache: