version: '3.5'

services:

  ruby_gem:
    image: roar
    build:
      context: .
#      target: "${TARGET}"
      dockerfile: mise/containers/ruby_gem/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - RUBY_VERSION='2.5'

