services:
  ruby:
    build:
      dockerfile: ./mise/containers/roro/Dockerfile.ruby
      tags: 
        - handsomefencer/ruby:3.3.0-alpine
  
  builder:
    build:
      dockerfile: ./mise/containers/roro/Dockerfile.builder
      tags: 
        - handsomefencer/roro:builder
    depends_on: 
      - ruby

