version: '3.2'

services:

  ruby_gem:
    image: roar
    build:
      context: .
      dockerfile: mise/containers/ruby_gem/Dockerfile
    volumes:
      - .:/usr/src
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - RUBY_VERSION='2.5'


volumes:
  gem_cache: