services:
  development: &development 
    build:
      context: .
      dockerfile: mise/containers/roro/Dockerfile.development
    depends_on: 
      - builder
    image: handsomefencer/roro/development
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src
      - /var/run/docker.sock:/var/run/docker.sock
      - gem_cache:/usr/local/bundle/gems

  dev:
    <<: *development

  test: &test
    <<: *development

  guard:
    <<: *test
    command: bundle exec guard
