version: '3.2'

services:

  ruby_gem:
    build:
      context: .
      dockerfile: mise/containers/ruby_image/Dockerfile
    volumes:
      - gem_cache:/gems
    environment:
      RUBY_VERSION: ${RUBY_VERSION}

volumes:
  gem_cache: