version: '3.5'

services:

  roro:
    build:
      context: .
      dockerfile: mise/containers/ruby_gem/Dockerfile
      # target: stripper
      target: production
    image: handsomefencer/roro
    user: "${UID}:${GID}"
    working_dir: /usr/src
    volumes:
      - .:/usr/src
      - gem_cache:/usr/local/bundle/gems

  guard:
    build:
      context: .
      dockerfile: mise/containers/ruby_gem/Dockerfile
    working_dir: /usr/src
    volumes:
      - .:/usr/src
    environment:
      - RAILS_ENV=development
    command: bundle exec guard --no-bundler-warning

volumes:
  gem_cache:
