version: '3.5'

services:

  ruby_gem:
    image: handsomefencer/roro
    build:
      context: .
      dockerfile: mise/containers/ruby_gem/Dockerfile
    environment:
      - RUBY_VERSION='2.5'

  dev:
    build:
      context: .
      dockerfile: mise/containers/ruby_gem/Dockerfile
    working_dir: /usr/src
    volumes:
      - .:/usr/src

  guard:
    build:
      context: .
      dockerfile: mise/containers/ruby_gem/Dockerfile
    working_dir: /usr/src
    volumes:
      - .:/usr/src
    environment:
      - RAILS_ENV=development
    command: bundle exec guard --no-bundler-warning
