services:
  production:
    build:
      dockerfile: mise/containers/roro/Dockerfile.production
      tags: 
        - handsomefencer/roro:production
    image: handsomefencer/roro
    volumes:
      - .:/usr/src
      - gem_cache:/usr/local/bundle/gems
