version: '3.2'

services:

  ruby_gem:
    build:
      context: .
      dockerfile: mise/containers/ruby_gem/Dockerfile
    volumes:
      - gem_cache:/gems
    environment:
      RUBY_VERSION: '2.5'

volumes:
  gem_cache: