services:
  development: &development 
    build:
      dockerfile: mise/containers/roro/Dockerfile.development
      tags: 
        - handsomefencer/roro:development
    image: handsomefencer/roro
    depends_on: 
      - builder
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src
      - /var/run/docker.sock:/var/run/docker.sock
      - gem_cache:/usr/local/bundle/gems

  dev: 
    <<: *development

  test: &test
    <<: *development

  test-all: 
    <<: *test
    command: bundle exec rake test
    environment: 
      DEBUGGERER: true

  guard:
    <<: *test
    command: bundle exec guard