version: '3.5'

services:

  dev:
    build:
      context: .
      dockerfile: mise/containers/ruby_gem/Dockerfile
      target: development
    image: handsomefencer/roro
    user: "${UID}:${GID}"
    working_dir: /usr/src
    volumes:
      - .:/usr/src

  prod:
    build:
      context: .
      dockerfile: mise/containers/ruby_gem/Dockerfile
      target: production
    image: handsomefencer/roro-prod
    user: "${UID}:${GID}"
    working_dir: /usr/src
    volumes:
      - .:/usr/src

  roro:
    build:
      context: .
      dockerfile: mise/containers/ruby_gem/Dockerfile
    image: handsomefencer/roro
    user: "${UID}:${GID}"
    working_dir: /usr/src
    volumes:
      - .:/usr/src

  guard:
    build:
      context: .
      dockerfile: mise/containers/ruby_gem/Dockerfile
    working_dir: /usr/src
    volumes:
      - .:/usr/src
    environment:
      - RAILS_ENV=development
    command: bundle exec guard --no-bundler-warning
