steps:
  - run: 
      name: Remove cached gem volumes to prevent clash
      command: |
        docker volume rm $(docker volume ls --filter name=test-adventures -q) 

  - run: 
      name: Artifact up using docker-compose
      command: |
        cd ${APP_NAME} 
        sudo docker-compose build 
        sudo docker-compose up -d

