steps:

  - run: 
      name: Artifact up using docker-compose
      command: |
        cd ${APP_NAME} 
        sudo docker-compose build 
        sudo docker-compose up -d
  - run: 
      name: Wait and try again on fail
      command: sleep 120
      when: on_fail
  - run: 
      name: Artifact up using docker-compose
      command: |
        cd ${APP_NAME} 
        sudo docker-compose build 
        sudo docker-compose up -d
      when: on_fail
