steps:
  - run: 
      name: Remove cached gem volumes to prevent clash
      command: docker volume rm ${APP_NAME}_gem_cache
  - run: 
      name: Artifact up using docker-compose
      command: |
        cd ${APP_NAME} 
        sudo docker-compose build 
        sudo docker-compose up -d

