steps:
  - run: 
      name: Copy artifact from roro container to host 
      command: |
        container=$(sudo docker ps -aqf "name=${APP_NAME}")
        echo "export container=${container}" >> "$BASH_ENV"
        cat $BASH_ENV
        sudo docker cp ${container}:/artifact ./${APP_NAME}
