steps:
  - run: 
      name: Artifact copy from container to host 
      command: |
        container=$(sudo docker ps -aqf "name=${APP_NAME}")
        echo "export container=${container}" >> "$BASH_ENV"
        cat $BASH_ENV
        sudo docker cp $(sudo docker ps -aqf "name=${APP_NAME}"):/artifact ./${APP_NAME}
