steps:
  - restore_cache:
      key: circlev2-{{ checksum "Gemfile.lock" }}
  - run: bundle config set --local path 'vendor/bundle'
  - run: bundle install --jobs=4 --retry=3
  - save_cache:
      key: circlev2-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle