parameters:
  answers:
    type: string
    default: "1\n2"
  os:
    type: executor
steps:
  - run: |
      rake install &&
      printf "<< parameters.answers >>\na$var\n" | roro rollon
  - run: echo 'success'
