---
jobs:
- test-adventures:
    filters:
      branches:
        only: development
    matrix:
      parameters:
        answers:
        - 1 1 1
        - 1 1 2
        - 1 2 1
        - 1 2 2
        - 1 3 1
        - 1 3 2
        - '2'
        os:
        - linux
