---
jobs:
- build
- test-adventures:
    requires:
    - build
    filters:
      branches:
        only:
        - adventures
    matrix:
      parameters:
        answers:
        - 1\n1\n1
        - 1\n1\n2
        os:
        - ruby
