---
jobs:
- test-adventures:
    filters:
      branches:
        only:
        - adventures
    matrix:
      parameters:
        answers:
        - 1\n1\n1\n1
        - 1\n1\n1\n2
        - 1\n1\n2\n1\n1
        - 1\n1\n2\n1\n2
        - 1\n1\n2\n2\n1
        - 1\n1\n2\n2\n2
        - 1\n2\n1\n1
        - 1\n2\n1\n2
        - 1\n2\n2\n1\n1
        - 1\n2\n2\n1\n2
        - 1\n2\n2\n2\n1
        - 1\n2\n2\n2\n2
        - 1\n3\n1\n1
        - 1\n3\n1\n2
        - 1\n3\n2\n1\n1
        - 1\n3\n2\n1\n2
        - 1\n3\n2\n2\n1
        - 1\n3\n2\n2\n2
        - 1\n4\n1\n1
        - 1\n4\n1\n2
        - 1\n4\n2\n1\n1
        - 1\n4\n2\n1\n2
        - 1\n4\n2\n2\n1
        - 1\n4\n2\n2\n2
        - '2'
        os:
        - machine-ubuntu
