---
jobs:
- build
- build-roro-image
- test-adventures:
    requires:
    - build-roro-image
    filters:
      branches:
        only:
        - machine-ubuntu
    matrix:
      parameters:
        answers:
        - 1\n1\n1
        - 1\n1\n2
        - 1\n2\n1
        - 1\n2\n2
        - 1\n3\n1
        - 1\n3\n2
        - '2'
        os:
        - machine-ubuntu
