---
jobs:
- test-rubies:
    filters:
      branches:
        only: rubies
    matrix:
      parameters:
        version:
        - '2.7'
        - '3.0'
        - '3.1'
        - '3.2'
        - '3.3'
