jobs:
  - test-rollon:
      filters:
        branches:
          only: main
      matrix:
        parameters:
          answers:
            - 1\n1
            - 1\n2
            - 1\n3
            - 1\n4
            - 1\n5
            - 2\n1
            - 2\n2\1\1
            - 2\n2\1\2
            - 3\n1
            - 3\n2
            - 4\n2
            - 4\n3
          os: [linux]

