---
jobs:
- test-rollon:
    matrix:
      parameters:
        answers:
        - 1\n1
        - 2\n1
        - 2\n2
        - 2\n3
        - 3\n1\n1\n1
        - 3\n1\n1\n2
        - 3\n1\n2\n1
        - 3\n1\n2\n2
        - 3\n2\n2\n1
        - 3\n2\n2\n2
        - 3\n2\n1\n2\n1\n1
        - 3\n2\n1\n2\n1\n2
        - 3\n2\n1\n2\n2\n1
        - 3\n2\n1\n2\n2\n2
        - 3\n2\n1\n1\n1\n1\n1
        - 3\n2\n1\n1\n1\n1\n2
        - 3\n2\n1\n1\n1\n2\n1
        - 3\n2\n1\n1\n1\n2\n2
        - 3\n2\n1\n1\n2\n1\n1
        - 3\n2\n1\n1\n2\n1\n2
        - 3\n2\n1\n1\n2\n2\n1
        - 3\n2\n1\n1\n2\n2\n2
        - 4\n1
        - 4\n2
        - 5\n2
        - 5\n3
        - 5\n1\n1\n1\n1
        os:
        - linux
