commands:
    artifact-copy:
        steps:
            - run:
                command: |
                    docker cp $(sudo docker ps -aqf "name=${APP_NAME}"):/artifact ./${APP_NAME}
                name: Artifact copy from container to host
    artifact-generate:
        steps:
            - run:
                command: |
                    docker run \
                      --name ${APP_NAME} \
                      -v ${PWD}:/${APP_NAME} \
                      -v /var/run/docker.sock:/var/run/docker.sock \
                      -u 0 \
                      -it handsomefencer/roro \
                      sh -c "printf '${ANSWERS}\na\n' | roro rollon"
                name: Artifact generate in roro container
    artifact-up:
        steps:
            - run:
                command: "cd ${APP_NAME} \ndocker-compose build app\ndocker-compose up -d app\n"
                name: Artifact up using docker-compose
    log-into-dockerhub:
        steps:
            - run:
                command: docker-compose run -e CI_KEY=${CI_KEY} --rm roro roro generate:exposed
                name: Expose credentials in mise/env/ci.env.enc
            - run:
                command: echo $(cat mise/env/ci.env) >> $BASH_ENV
                name: Export credentials from mise/env/ci.env
            - run:
                command: |
                    echo ${DOCKERHUB_TOKEN} | docker login \
                      -u ${DOCKERHUB_USERNAME} \
                      --password-stdin
                name: Log into Docker Hub
            - run:
                command: "docker tag handsomefencer/roro handsomefencer/roro:latest \ndocker tag handsomefencer/roro handsomefencer/roro:${CIRCLE_SHA1} \n"
                name: Tag image with latest and circle (git) sha
            - run:
                command: |-
                    docker image push handsomefencer/roro:latest
                    docker image push handsomefencer/roro:${CIRCLE_SHA1}
                name: Push tagged images
    restore-and-save-cache:
        steps:
            - restore_cache:
                key: circlev2-{{ checksum "Gemfile.lock" }}
            - run: bundle config set --local path 'vendor/bundle'
            - run: bundle install --jobs=4 --retry=3
            - save_cache:
                key: circlev2-{{ checksum "Gemfile.lock" }}
                paths:
                    - vendor/bundle
    roro-image-build:
        steps:
            - run:
                command: docker-compose build roro
                name: Build Roro image
    set-variables:
        steps:
            - run:
                command: echo "APP_NAME=${CIRCLE_JOB//\\n/_}-${CIRCLE_WORKFLOW_JOB_ID}" >> "$BASH_ENV"
                name: Store answers and app_name variables
executors:
    docker-cimg-base:
        docker:
            - image: cimg/base:2023.06
    docker-cimg-ruby:
        docker:
            - image: cimg/ruby:<<parameters.version>>
        parameters:
            version:
                default: 3.2.2
                description: version tag
                type: string
    machine-osx:
        macos:
            xcode: 14.2.0
    machine-ubuntu:
        machine:
            docker_layer_caching: true
            image: ubuntu-2204:2023.04.2
    machine-ubuntu-no-caching:
        machine:
            docker_layer_caching: false
            image: ubuntu-2204:2023.04.2
    ruby-alpine:
        docker:
            - image: ruby:<<parameters.version>>-alpine
        parameters:
            version:
                default: 3.2.2
                description: version tag
                type: string
jobs:
    build:
        executor: machine-ubuntu
        steps:
            - checkout
            - restore-and-save-cache
    release:
        executor: docker-cimg-ruby
        steps:
            - checkout
            - run: |
                git config --global user.email "fred.schoeneman@gmail.com"
                git config --global user.name "Fred Schoeneman"
            - run: gem install gem-release
            - run: gem bump
            - run: gem release
    roro-image-build:
        executor: machine-ubuntu
        steps:
            - checkout
            - roro-image-build
    roro-image-push:
        executor: machine-ubuntu
        steps:
            - checkout
            - log-into-dockerhub
            - roro-image-build
            - run: "docker tag handsomefencer/roro handsomefencer/roro:latest \ndocker tag handsomefencer/roro handsomefencer/roro:${CIRCLE_SHA1} \n"
            - run: |-
                docker image push handsomefencer/roro:latest
                docker image push handsomefencer/roro:${CIRCLE_SHA1}
    test:
        executor: machine-ubuntu
        parallelism: 5
        steps:
            - checkout
            - restore-and-save-cache
            - run:
                command: |
                    export DEBUGGERER='true'
                    circleci tests glob "test/**/*_test.rb" | \
                    circleci tests run \
                    --command="xargs bundle exec rake test" \
                    --split-by=timings
    test-rubies:
        executor: docker-cimg-ruby
        parameters:
            version:
                default: "3.0"
                description: version tag
                type: string
        steps:
            - checkout
            - run: bundle exec rake test TEST=test/roro/ci/*_test.rb
version: 2.1
workflows:
    gem-release:
        jobs:
            - release:
                filters:
                    branches:
                        only:
                            - gem-release
    release-image:
        jobs:
            - roro-image-push:
                filters:
                    branches:
                        only:
                            - main
    rollon-tests:
        jobs:
            - build
            - test:
                filters:
                    branches:
                        only:
                            - development
                requires:
                    - build
    rubies:
        jobs:
            - test-rubies:
                filters:
                    branches:
                        only: rubies
                matrix:
                    parameters:
                        version:
                            - "2.7"
                            - "3.0"
                            - "3.1"
                            - "3.2"
                            - "3.3"

