version: 2.1

defaults: &defaults
  executor: exec-machine
  working_directory: ~/project
  environment:
    RORO_ENV: ci

major_only: &major_only
  filters:
    branches:
      only: master
      
executors: 
  exec-machine: 
    machine: 
      image: circleci/classic:latest
  exec-ruby: 
    docker:
      - image: cimg/ruby:2.7

jobs:

  build:
    <<: *defaults
    steps:
      - checkout
  
  test-rollon-rails: 
    executor: ruby-executor
    steps: 
      - checkout 
      - setup_remote_docker:
          version: 19.03.12
      - run: |
          rake install 
          mkdir greenfield
          cd greenfield
          (yes || true) | roro greenfield
      - run: echo 'succesfully greenfielded'
      - run: docker-compose up -d
      - run: echo 'successfully built greenfielded app'
      - run: docker-compose exec app bin/rails db:create
      - run: docker-compose exec app bin/rails db:migrate
      - run: docker-compose exec app bin/rails test
      - run: echo 'successfully ran (nonexistent) tests!'
  
  test:
    <<: *defaults
    steps:
      - checkout
      - run: RUBY_VERSION=2.5 docker-compose build ruby_gem
      - run: RUBY_VERSION=2.5 docker-compose up -d --force-recreate ruby_gem
      - run: RUBY_VERSION=2.5 docker-compose run ruby_gem bundle exec rake test
      - run: RUBY_VERSION=2.6 docker-compose build ruby_gem
      - run: RUBY_VERSION=2.6 docker-compose up -d --force-recreate ruby_gem
      - run: RUBY_VERSION=2.6 docker-compose run ruby_gem bundle exec rake test
      - run: RUBY_VERSION=2.7 docker-compose build ruby_gem
      - run: RUBY_VERSION=2.7 docker-compose up -d --force-recreate ruby_gem
      - run: RUBY_VERSION=2.7 docker-compose run ruby_gem bundle exec rake test    
      
  release:
    <<: *defaults
    steps:
      - checkout
      - run: gem install roro
      - run: roro generate::exposed ci
      - run: | 
          echo $(cat ./roro/containers/ruby_image/ci.env) >> $BASH_ENV
          source $BASH_ENV
      - run: chmod +x ./.circleci/setup-gem-credentials.sh
      - run: ./.circleci/setup-gem-credentials.sh
      - run: chmod 0600 ~/.gem/credentials
      - run: git checkout .
      - run: gem release
  
workflows:
  version: 2
    
  build-cli: 
    jobs: 
      - build:
        <<: *major_only
      - test-rollon-rails: 
        <<: *major_only
      - test:
        <<: *major_only
      - release:
          requires: 
            - build
          filters: 
            branches: 
              only: release