commands:
    restore-and-save-cache:
        steps:
            - restore_cache:
                key: circlev2-{{ checksum "Gemfile.lock" }}
            - run: bundle config set --local path 'vendor/bundle'
            - run: bundle check || bundle install --jobs=4 --retry=3
            - run: gem install roro
            - save_cache:
                key: circlev2-{{ checksum "Gemfile.lock" }}
                paths:
                    - vendor/bundle
executors:
    alpine:
        docker:
            - image: ruby:3.2.1-alpine
    linux:
        docker:
            - image: cimg/ruby:3.2.2
    ruby:
        docker:
            - image: cimg/ruby:<<parameters.version>>
        parameters:
            version:
                default: 3.2.2
                description: version tag
                type: string
jobs:
    build:
        executor:
            name: ruby
        steps:
            - checkout
            - run: whoami
            - run: echo ${USER}
    release:
        executor:
            name: ruby
        steps:
            - checkout
            - run: |
                git config --global user.email "fred.schoeneman@gmail.com"
                git config --global user.name "Fred Schoeneman"
            - run: gem install gem-release
            - run: gem bump
            - run: gem release
    test-adventures:
        executor: << parameters.os >>
        parameters:
            answers:
                default: 1\1
                type: string
            os:
                default: linux
                type: executor
        steps:
            - checkout
            - setup_remote_docker:
                version: 19.03.12
            - restore-and-save-cache
            - run: "mkdir -p sandbox \ncd sandbox \nprintf \"<< parameters.answers >>\\na$var\\n\" | roro rollon\nls    \n"
            - run: sudo docker ps
    test-rubies:
        executor:
            name: ruby
            version: <<parameters.version>>
        parameters:
            version:
                default: "3.0"
                description: version tag
                type: string
        steps:
            - checkout
            - run: gem install bundler
            - run: bundle
            - run: bundle exec rake test:test
            - run: bundle exec rake test:stacks
version: 2.1
workflows:
    adventures:
        jobs:
            - test-adventures:
                filters:
                    branches:
                        only: development
                matrix:
                    parameters:
                        answers:
                            - 1 1 1
                            - 1 1 2
                            - 1 2 1
                            - 1 2 2
                            - 1 3 1
                            - 1 3 2
                            - "2"
                        os:
                            - linux
    gem-release:
        jobs:
            - build
            - release:
                filters:
                    branches:
                        only: main
    rubies:
        jobs:
            - test-rubies:
                filters:
                    branches:
                        only: dev
                matrix:
                    parameters:
                        version:
                            - "3.0"
                            - "2.7"
                            - "2.6"
                            - "2.5"

