defaults: &defaults
  working_directory: /repo

version: 2

jobs:

  build:
    docker:
       - image: circleci/ruby:2.5.3
    steps:
      - checkout
      - setup_remote_docker
      # - run: bundle
      # - run: rake install
      # - run: rake test
      # - run: ls -a
      # - run: rm -rf tmp/*
      # - run: bundle
      # - run: rake install
      - run:
          name: Greenfield
          working_directory: sooperdooper
          command: |
            bundle
            sleep 2s
            rake install
            sleep 2s
            roro greenfield

      - run:
          name: db:create
          working_directory: sooperdooper
          command: docker-compose run web bin/rails db:create
      - run: curl -Is localhost:3000 | head -n 1

      #       docker-compose run web rails new . --force --database=postgresql --skip-bundle
      #       bundle
      #       rails db:create db:migrate
      #       rails s -d
      #       killall -9 rails
      # - run:
      #     name: Rollon
      #     command: |
      #       mkdir -p sooperdooper
      #       cd sooperdooper
      #       roro greenfield
      #       rails new . --force --database=postgresql
      #       chown -R $USER:$USER -R .
      #       bundle
      #       rails db:create db:migrate
      #       rails s -d
      #       curl -Is localhost:3000 | head -n 1
      #       killall -9 rails
      #

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
