defaults: &defaults
  working_directory: /tmp

version: 2

jobs:

  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.5
    steps:

      - checkout
      - run: gem install bundler
      - run: bundle
      - run: rake install
      - run: rake test
      - run: mkdir -p newapp
      - run: cd newapp && roro greenfield
      - run: cd newapp && docker-compose run --rm app rails new . --database=postgresql --skip
      - run: cd newapp && docker-compose build
      - run: cd newapp && docker-compose run app bin/rails db:create db:migrate
      - run: cd newapp && docker-compose up

#   push:
#     machine: true
#     steps:
#       - checkout
#       - run: gem install handsome_fencer-circle_c_i
#       - run: handsome_fencer-circle_c_i expose circleci
#       - run: handsome_fencer-circle_c_i expose development
#       - run: echo 'source docker/env_files/circleci.env' >> $BASH_ENV
#       - run: docker-compose build app web
#       - run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
#       - run:
#           name: Tag app image
#           command: docker tag $(docker images | grep project_app | awk '{ print $3 }') ${DOCKERHUB_ORG_NAME}/${APP_NAME}_app:$DEPLOY_TAG
#       - run:
#           name: Tag web image
#           command: docker tag $(docker images | grep project_web | awk '{ print $3 }') ${DOCKERHUB_ORG_NAME}/${APP_NAME}_web:$DEPLOY_TAG
#
#
#       - run: docker push ${DOCKERHUB_ORG_NAME}/${APP_NAME}_app:$DEPLOY_TAG
#       - run: docker push ${DOCKERHUB_ORG_NAME}/${APP_NAME}_web:$DEPLOY_TAG
#
#   deploy:
#     machine: true
#     steps:
#       - checkout
#       - add_ssh_keys
#       - run: gem install handsome_fencer-circle_c_i
#       - run: handsome_fencer-circle_c_i expose circleci
#       - run: handsome_fencer-circle_c_i expose development
#       - run: echo 'source docker/env_files/circleci.env' >> $BASH_ENV
#
#       - run: rake --rakefile .circleci/Rakefile
#
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      # - deploy:
      #     requires:
      #       - push
      #     filters:
      #       branches:
      #         only: master
