aliases:
  - &workspace-location
    at: /tmp/workspace
  - &copy-ci-dotenv | 
    cp -rf /tmp/workspace/roro .
  - &source-ci-variables | 
    echo 'source roro/containers/app/ci.env' >> $BASH_ENV
    source $BASH_ENV

commands:

  run-test-case:
    parameters:
      answers:
        type: string
        default: "1\n2"
      os:
        type: executor
    steps:
      - run: |
          rake install &&
          printf "<< parameters.answers >>\ny\ny\ny\ny\ny\ny\ny$var\n" | roro rollon
      - run: echo 'success'
      - run: docker-compose down

  run-tests:
    parameters:
      ruby-version:
        type: string
        default: '2.5'
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: |
          RUBY_VERSION=<< parameters.ruby-version >>
          sudo docker-compose build ruby_gem &&
          sudo docker-compose up -d --force-recreate ruby_gem &&
          sudo docker-compose run ruby_gem bundle exec rake test

defaults: &defaults
  executor: ruby-executor
  working_directory: ~/project

major_only: &major_only
  filters:
    branches:
      only: master

release: &release
  filters:
    branches:
      only: release

version: 2.1

executors:

  machine-executor:
    machine: true
  ruby-executor:
    docker:
      - image: cimg/ruby:2.7
  linux:
    docker:
      - image: cimg/ruby:2.7
  mac:
    macos:
      xcode: 11.4

jobs:

  build:
    <<: *defaults
    steps:
      - checkout

  test:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
        version: 19.03.12
      - run-tests:
        ruby-version: '2.7'

  test-rollon:
    parameters:
      answers:
        type: string
        default: "1\n4"
      os:
        type: executor
        default: linux
    executor: << parameters.os >>
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run-test-case:
          answers: << parameters.answers >>
          os: << parameters.os >>

  release:
    <<: *defaults
    steps:
      - checkout
      - run: gem install roro
      - run: roro generate::exposed ci
      - run: | 
          echo $(cat ./roro/containers/ruby_image/ci.env) >> $BASH_ENV
          source $BASH_ENV
      - run: chmod +x ./.circleci/setup-gem-credentials.sh
      - run: ./.circleci/setup-gem-credentials.sh
      - run: chmod 0600 ~/.gem/credentials
      - run: git checkout .
      - run: gem release

workflows:
  version: 2.1
  test-all-cases:
    jobs:
      - test-rollon:
          <<: *major_only
          matrix:
            parameters:
              answers: ["1\n1", "1\n2", "1\n3", "1\n4", "1\n5", "2\n1", "3\n1", "3\n2"]
              os: [linux]
    
  build-cli: 
    jobs: 
      - build: 
          <<: *major_only
          <<: *release
      - test-rollon:
          <<: *major_only
#      - test:
#          <<: *major_only
      
      - release:
          requires: 
            - build
          <<: *release
