defaults: &defaults
  working_directory: /tmp

version: 2

jobs:

  build:
    docker:
       - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - setup_remote_docker
      - run: gem install bundler
      - run: rake install
      - run: bundle
      - run:
          name: Basic Greenfield
          command: |
            mkdir -p sooperdooper
            cd sooperdooper
            roro greenfield
            docker-compose run app rails new . --force --database=postgresql
            chown -R $USER:$USER -R .
            bundle
            rails db:create db:migrate
            rails s -d
      - run: curl -Is localhost:3000 | head -n 1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
