commands:
    restore-and-save-cache:
        steps:
            - restore_cache:
                key: circlev2-{{ checksum "Gemfile.lock" }}
            - run: bundle config set --local path 'vendor/bundle'
            - run: bundle check || bundle install --jobs=4 --retry=3
            - run: gem build roro.gemspec
            - save_cache:
                key: circlev2-{{ checksum "Gemfile.lock" }}
                paths:
                    - vendor/bundle
executors:
    ruby:
        docker:
            - image: cimg/ruby:<<parameters.version>>
        parameters:
            version:
                default: 3.2.2
                description: version tag
                type: string
jobs:
    build:
        executor:
            name: ruby
        steps:
            - checkout
            - restore-and-save-cache
            - setup_remote_docker:
                docker_layer_caching: true
                version: 20.10.24
            - run: sudo docker-compose build roro
    release:
        executor:
            name: ruby
        steps:
            - checkout
            - run: |
                git config --global user.email "fred.schoeneman@gmail.com"
                git config --global user.name "Fred Schoeneman"
            - run: gem install gem-release
            - run: gem bump
            - run: gem release
    test-adventures:
        executor: << parameters.os >>
        parameters:
            answers:
                default: 1\1
                type: string
            os:
                default: ruby
                type: executor
        steps:
            - setup_remote_docker:
                docker_layer_caching: true
                version: 19.03.12
            - run: |
                answers=<< parameters.answers >>
                name=${answers//\\/_}
                sudo docker run \
                  --name ${name} \
                  -v ${PWD}:/${name} \
                  -v /var/run/docker.sock:/var/run/docker.sock \
                  -u 0 \
                  -it handsomefencer/roro:latest \
                  sh -c "printf '<< parameters.answers >>\na\n' | roro rollon"

                container_id="$(sudo docker ps -aqf "name=${name}")"
                sudo docker cp ${container_id}:/${name}/. .
            - run: sudo docker-compose build
            - run: sudo docker-compose up -d
        working_directory: ~/sandbox
    test-rubies:
        executor:
            name: ruby
            version: <<parameters.version>>
        parameters:
            version:
                default: "3.0"
                description: version tag
                type: string
        steps:
            - checkout
            - run: gem install bundler
            - run: bundle
            - run: bundle exec rake test:test
            - run: bundle exec rake test:stacks
version: 2.1
workflows:
    adventures:
        jobs:
            - build
            - test-adventures:
                filters:
                    branches:
                        only:
                            - adventures
                matrix:
                    parameters:
                        answers:
                            - 1\n1\n1
                            - 1\n1\n2
                            - 1\n2\n1
                            - 1\n2\n2
                            - 1\n3\n1
                            - 1\n3\n2
                            - "2"
                        os:
                            - ruby
                requires:
                    - build
    gem-release:
        jobs:
            - build
            - release:
                filters:
                    branches:
                        only:
                            - adventures
    rubies:
        jobs:
            - test-rubies:
                filters:
                    branches:
                        only: adventures
                matrix:
                    parameters:
                        version:
                            - "3.0"
                            - "2.7"
                            - "2.6"
                            - "2.5"

