defaults: &defaults
  working_directory: /repo

version: 2

jobs:

  build:
    machine: true
    steps:
      - checkout

  test:
    docker:
       - image: circleci/ruby:2.5.3
    steps:
      - checkout
      - setup_remote_docker
      - run: gem install bundler
      - run: bundle
      - run: rake install
      - run: mkdir tmp
      - run: docker-compose up app

  test_all:
    docker:
       - image: circleci/ruby:2.5.3
    steps:
      - checkout
      - setup_remote_docker
      - run: gem install bundler
      - run: bundle
      - run: rake install
      - run: mkdir tmp
      - run: docker-compose up

  build-greenfield:
    machine: true
    steps:
      - checkout
      - run: bundle
      - run: rake install
      - run:
          name: Greenfield
          working_directory: sooperdooper
          command: |
            bundle
            sleep 2s
            rake install
            sleep 5s
            roro greenfield
            sleep 5s
            curl -Is localhost:3000 | head -n 1

  build-rollon:
    machine: true
    steps:
      - checkout
      - run: bundle
      - run: rake install
      - run:
          name: Rollon
          working_directory: test_apps/dummy
          command: |
            roro rollon
            docker-compose up -d
            docker-compose exec app bin/rails db:create
            docker-compose exec app rake test
            curl -Is localhost:3000 | head -n 1

  push-release:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
      - setup_remote_docker
      - run: gem install bundler
      - run: bundle
      - run: rake install
      - run: roro expose
      - run: echo 'source docker/env_files/circleci.env' >> $BASH_ENV
      - run: bash .circleci/setup-gem-credentials.sh
      - run: git config credential.helper 'cache --timeout=120'
      - run: git config user.email $GIT_EMAIL
      - run: git config user.name $GIT_NAME
      - run: git add .
      - run: git commit -m "Update release branch via CircleCI"
      - run: git checkout -b release
      - run: git push -q --force https://${GITHUB_PERSONAL_TOKEN}@github.com/schadenfred/roro.git release

  release:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
      - setup_remote_docker
      - run: gem install bundler
      - run: bundle
      - run: rake install
      - run: roro expose
      - run: echo 'source docker/env_files/circleci.env' >> $BASH_ENV
      - run: bash .circleci/setup-gem-credentials.sh
      - run: gem install gem-release
      - run: gem release

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test:
          filters:
            branches:
              only:
                - /feature-.*/
      - build-greenfield:
          filters:
            branches:
              only:
                - build-greenfield
                - development
                - master
      - build-rollon:
          filters:
            branches:
              only:
                - build-rollon
                - development
                - master
      - test_all:
          filters:
            branches:
              only:
                - development
                - master

      - release:
          filters:
            branches:
              only:
                - release

      - push-release:
          filters:
            branches:
              only:
                - push-release
