defaults: &defaults
  working_directory: /repo

version: 2

jobs:
  build:
    docker:
       - image: circleci/ruby:2.5.3
    steps:
      - checkout

  test:
    docker:
       - image: circleci/ruby:2.5.3
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle
      - run: rake install
      - run: rake test

  build-greenfield:
    machine: true
    steps:
      - checkout
      - run: bundle
      - run: rake install
      - run:
          name: Greenfield
          working_directory: sooperdooper
          command: |
            bundle
            sleep 2s
            rake install
            sleep 5s
            roro greenfield
            sleep 5s
            curl -Is localhost:3000 | head -n 1

      # - run:
      #     name: Greenfield
      #     working_directory: sooperdooper
      #     command: curl -Is localhost:3000 | head -n 1

      #       docker-compose run web rails new . --force --database=postgresql --skip-bundle
      #       bundle
      #       rails db:create db:migrate
      #       rails s -d
      #       killall -9 rails
      # - run:
      #     name: Rollon
      #     command: |
      #       mkdir -p sooperdooper
      #       cd sooperdooper
      #       roro greenfield
      #       rails new . --force --database=postgresql
      #       chown -R $USER:$USER -R .
      #       bundle
      #       rails db:create db:migrate
      #       rails s -d
      #       curl -Is localhost:3000 | head -n 1
      #       killall -9 rails
      #

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test
      - build-greenfield:
          filters:
            branches:
              only: greenfield
