commands:
    restore-and-save-cache:
        steps:
            - restore_cache:
                key: circlev2-{{ checksum "Gemfile.lock" }}
            - run: bundle config set --local path 'vendor/bundle'
            - run: bundle check || bundle install --jobs=4 --retry=3
            - run: rake install
            - save_cache:
                key: circlev2-{{ checksum "Gemfile.lock" }}
                paths:
                    - vendor/bundle
executors:
    ruby:
        docker:
            - image: cimg/ruby:<<parameters.version>>
        parameters:
            version:
                default: 3.2.2
                description: version tag
                type: string
jobs:
    build:
        executor:
            name: ruby
        steps:
            - checkout
            - setup_remote_docker:
                docker_layer_caching: true
            - run: sudo docker-compose build
            - run: sudo docker-compose run --rm roro roro rollon
    release:
        executor:
            name: ruby
        steps:
            - checkout
            - run: |
                git config --global user.email "fred.schoeneman@gmail.com"
                git config --global user.name "Fred Schoeneman"
            - run: gem install gem-release
            - run: gem bump
            - run: gem release
    test-adventures:
        executor: << parameters.os >>
        parameters:
            answers:
                default: 1\1
                type: string
            os:
                default: ruby
                type: executor
        steps:
            - checkout
            - setup_remote_docker:
                version: 19.03.12
            - restore-and-save-cache
            - run: |
                docker-compose build roro
                docker-compose run --rm roro \
                printf "<< parameters.answers >>\na\n" | roro rollon
            - run: sudo docker ps
    test-rubies:
        executor:
            name: ruby
            version: <<parameters.version>>
        parameters:
            version:
                default: "3.0"
                description: version tag
                type: string
        steps:
            - checkout
            - run: gem install bundler
            - run: bundle
            - run: bundle exec rake test:test
            - run: bundle exec rake test:stacks
version: 2.1
workflows:
    adventures:
        jobs:
            - test-adventures:
                filters:
                    branches:
                        only: development
                matrix:
                    parameters:
                        answers:
                            - 1\n1\n1
                            - 1\n1\n2
                            - 1\n2\n1
                            - 1\n2\n2
                            - 1\n3\n1
                            - 1\n3\n2
                            - "2"
                        os:
                            - ruby
    gem-release:
        jobs:
            - build
            - release:
                filters:
                    branches:
                        only: main
    rubies:
        jobs:
            - test-rubies:
                filters:
                    branches:
                        only: dev
                matrix:
                    parameters:
                        version:
                            - "3.0"
                            - "2.7"
                            - "2.6"
                            - "2.5"

