version: 2.1

jobs:

  build:
    machine: true
    steps:
      - checkout
  
  test-cli: 
    machine: true 
    steps: 
      - checkout 
      - run: |
          rake install 
          mkdir greenfield
          cd greenfield
          echo "y" | roro greenfield

  
  test:
    machine: true
    steps:
      - checkout
      - run: RUBY_VERSION=2.5 docker-compose build ruby_gem
      - run: RUBY_VERSION=2.5 docker-compose up -d --force-recreate ruby_gem
      - run: RUBY_VERSION=2.5 docker-compose run ruby_gem bundle exec rake test
      - run: RUBY_VERSION=2.6 docker-compose build ruby_gem
      - run: RUBY_VERSION=2.6 docker-compose up -d --force-recreate ruby_gem
      - run: RUBY_VERSION=2.6 docker-compose run ruby_gem bundle exec rake test
      - run: RUBY_VERSION=2.7 docker-compose build ruby_gem
      - run: RUBY_VERSION=2.7 docker-compose up -d --force-recreate ruby_gem
      - run: RUBY_VERSION=2.7 docker-compose run ruby_gem bundle exec rake test    
      
  release:
    machine: true
    steps:
      - checkout
      - run: gem install roro
      - run: roro generate::exposed ci
      - run: | 
          echo $(cat ./roro/containers/ruby_image/ci.env) >> $BASH_ENV
          source $BASH_ENV
      - run: chmod +x ./.circleci/setup-gem-credentials.sh
      - run: ./.circleci/setup-gem-credentials.sh
      - run: chmod 0600 ~/.gem/credentials
      - run: git checkout .
      - run: gem release
  
workflows:
  version: 2
    
  build-release: 
    jobs: 
      - build
      - test-cli: 
          filters: 
            branches: 
              only: development
      - test:
          filters: 
            branches: 
              only: master
      
      - release:
          requires: 
            - build
          filters: 
            branches: 
              only: release