commands:
    run-test-case:
        parameters:
            answers:
                default: |-
                    1
                    2
                type: string
            os:
                type: executor
        steps:
            - run: |
                rake install &&
                printf "<< parameters.answers >>\na$var\n" | roro rollon
            - run: echo 'success'
executors:
    linux:
        docker:
            - image: cimg/ruby:2.7
    mac:
        macos:
            xcode: 11.4
    ruby:
        docker:
            - image: cimg/ruby:<<parameters.version>>
        parameters:
            version:
                default: "2.5"
                description: version tag
                type: string
    ruby-executor:
        docker:
            - image: cimg/ruby:2.7
jobs:
    build:
        executor:
            name: ruby
        steps:
            - checkout
    release:
        executor:
            name: ruby
        steps:
            - checkout
            - run: |
                git config --global user.email "fred.schoeneman@gmail.com"
                git config --global user.name "Fred Schoeneman"
            - run: gem install gem-release
            - run: gem bump
            - run: gem release
    test:
        executor:
            name: ruby
            version: <<parameters.version>>
        parameters:
            version:
                default: "3.0"
                description: version tag
                type: string
        steps:
            - checkout
            - run: gem install bundler
            - run: bundle
            - run: bundle exec rake test
    test-rollon:
        executor: << parameters.os >>
        parameters:
            answers:
                default: 1\1
                type: string
            os:
                default: linux
                type: executor
        steps:
            - checkout
            - setup_remote_docker:
                version: 19.03.12
            - run: |
                rake install &&
                printf "<< parameters.answers >>\na$var\n" | roro rollon
            - run: echo 'success'
version: 2.1
workflows:
    gem-release:
        jobs:
            - build
            - release:
                requires:
                    - build
    test-matrix-rollon:
        jobs:
            - test-rollon:
                filters:
                    branches:
                        only: main
                matrix:
                    parameters:
                        answers:
                            - 1\n1
                            - 1\n2
                            - 1\n3
                            - 1\n4
                            - 1\n5
                            - 2\n1
                            - 2\n2\1\1
                            - 2\n2\1\2
                            - 3\n1
                            - 3\n2
                            - 4\n2
                            - 4\n3
                        os:
                            - linux
    test-matrix-rubies:
        jobs:
            - test:
                filters:
                    branches:
                        only: main
                matrix:
                    parameters:
                        version:
                            - "2.5"
                            - "2.6"
                            - "2.7"
                            - "3.0"

