executor:
  name: ruby
steps:
  - checkout
  - run: |
      git config --global user.email "fred.schoeneman@gmail.com"
      git config --global user.name "Fred Schoeneman"
  - run: gem install gem-release
  - run: gem bump
  - run: gem release