executor: machine-ubuntu
steps:
  - checkout
  - run: docker-compose run -e CI_KEY=${CI_KEY} --rm roro roro generate:exposed
  - run: |
      echo ${DOCKERHUB_TOKEN} | docker login \
        -u ${DOCKERHUB_USERNAME} \
        --password-stdin
  - run: |
      docker tag handsomefencer/roro handsomefencer/roro:latest 
      docker tag handsomefencer/roro handsomefencer/roro:${CIRCLE_SHA1} 
  - run: |
      docker image push handsomefencer/roro:latest
      docker image push handsomefencer/roro:${CIRCLE_SHA1}