executor: machine-ubuntu
steps:
  - checkout
  - run: docker run -e CI_KEY=${CI_KEY} --rm roro roro generate:exposed
  - run: echo $(cat mise/env/ci.env) >> $BASH_ENV
  - run: |
      echo "token\:    ${DOCKERHUB_TOKEN}"
      echo "username\: ${DOCKERHUB_PASSWORD}"
  - run: |
      sudo docker tag handsomefencer/roro handsomefencer/roro:latest 
      sudo docker tag handsomefencer/roro handsomefencer/roro:${CIRCLE_SHA1} 
  - run: |
      echo ${DOCKERHUB_TOKEN} | docker login \
        -u ${DOCKERHUB_USERNAME} \
        --password-stdin
      docker image push handsomefencer/roro:latest
      docker image push handsomefencer/roro:${CIRCLE_SHA1}