executor: machine-ubuntu
steps:
  - checkout
  - log-into-dockerhub
  - run: |
      docker tag handsomefencer/roro handsomefencer/roro:latest 
      docker tag handsomefencer/roro handsomefencer/roro:${CIRCLE_SHA1} 
  - run: |
      docker image push handsomefencer/roro:latest
      docker image push handsomefencer/roro:${CIRCLE_SHA1}