executor: machine-ubuntu
parallelism: 5
steps:
  - checkout
  - restore-and-save-cache
  - run: 
      name: run tests 
      command: DEBUGGERER='true' bundle exec rake test:stories
      when: always
  - store_test_results:
      path: test-results