parameters:
  version:
    description: "version tag"
    default: "3.0"
    type: string
executor: docker-cimg-ruby
steps:
  - checkout
  - run: docker-compose build test 
  - run: docker-compose run --rm test sh -c "DEBUGGERER='true' rake test"