executor: machine-ubuntu
parallelism: 5
steps:
  - checkout
  - run:
      name: Set ruby version to 3.2.1
      command: |
          rvm install 3.2.1
          echo . $(rvm 3.2.1 do rvm env --path) >> $BASH_ENV
  - run: bundle 
  - run: DEBUGGERER='true' rake test
  - run: |
      TEST=$(circleci tests glob "test/**/*_test.rb" | circleci tests split)
      rake $TEST