parameters:
  version:
    description: "version tag"
    default: "3.0"
    type: string
  folder:
    description: "folder in test/roro/<folder>"
    default: "cli"
    type: string
docker:
  - image: cimg/ruby:<<parameters.version>>
steps:
  - checkout
  - run: bundle
  - run: bundle exec rake test TEST=test/roro/<<parameters.folder>>/*_test.rb