parameters:
  version:
    description: "version tag"
    default: "3.0"
    type: string
executor: docker-cimg-ruby
steps:
  - checkout
  - run: gem install bundler
  - run: bundle
  - run: bundle exec rake test