executor: docker-cimg-ruby
parallelism: 5
steps:
  - checkout
  - setup_remote_docker:
      version: 20.10.24
  - restore-and-save-cache
  - run: 
      name: Which ruby?
      command: ruby -v
  - run: 
      name: Which docker?
      command: docker -v
  - run: 
      name: Which docker-compose?
      command: docker-compose -v
  - run: |
      TEST=$(circleci tests glob "test/**/*/_test.rb" | circleci tests split)
      DEBUGGERER='true' bundle exec rake test $TEST
  - store_test_results:
      path: .circleci/test-results