executor: machine-ubuntu
parallelism: 5
steps:
  - checkout
  - restore-and-save-cache
  - run: 
      name: Which ruby?
      command: ruby -v
  - run: 
      name: Which docker?
      command: docker -v
  - run: 
      name: Which docker-compose?
      command: docker-compose -v
  - run: |
      TEST=$(circleci tests glob "test/**/*/_test.rb" | circleci tests split)
      DEBUGGERER='true' bundle exec rake test $TEST
  - store_test_results:
      path: test/test-results