executor: machine-ubuntu
parallelism: 5
parameters:
  database:
    description: "database"
    default: "postgres"
    type: string
steps:
  - checkout
  - restore-and-save-cache
  - run:
      command: |
        export DEBUGGERER='true' 
        circleci tests glob "test/roro/stacks/**/*_test.rb" | \
        circleci tests split > /tmp/stack_tests \
        bundle exec rake test $(cat /tmp/stack-tests)