parameters:
  answers:
    type: string
    default: 1\1
  os:
    type: executor
    default: linux
executor: << parameters.os >>
steps:
  - checkout
  - setup_remote_docker:
      version: 19.03.12
  - restore-and-save-cache
  - run: | 
      mkdir -p sandbox 
      cd sandbox 
      printf "<< parameters.answers >>\na$var\n" | roro rollon
      ls    
  - run: sudo docker ps