parameters:
  version:
    description: "version tag"
    default: "3.0"
    type: string
executor:
  name: ruby
  version: <<parameters.version>>
steps:
  - checkout
  - run: gem install bundler
  - run: bundle
  - run: bundle exec rake test:test
  - run: bundle exec rake test:stacks