executor: docker-cimg-ruby
parallelism: 5
steps:
  - checkout
  - setup_remote_docker
  - run: 
      name: Which ruby?
      command: ruby -v
  - run: bundle 
  - run: |
      TEST=$(circleci tests glob "test/**/*/_test.rb" | circleci tests split)
      rake $TEST