executor: machine-ubuntu
parallelism: 5
steps:
  - checkout
  - restore-and-save-cache
  - run:
      command: |
        export DEBUGGERER='true'
        circleci tests glob "test/**/*_test.rb" | \
        circleci tests run \
        --command="xargs DEBUGGERER='true' bundle exec rake test" \
        --split-by=timings
  # - run: mkdir ~/rspec

  # - run: 
  #     name: run tests 
  #     command: DEBUGGERER='true' bundle exec rake test:stories
  #     when: always

  # - run:
  #     command: bundle exec rake test
  #     when: always
  #     - store_test_results:
  #         path: test/reports

  # - store_test_results:
  #     path: test-results


  # - run: mkdir ~/rspec
  # - run:
  #     command: |
  #       circleci tests glob "spec/**/*_spec.rb" | \
  #       circleci tests run \
  #       --command="xargs bundle exec rake test -o ~/rspec/rspec.xml" --verbose --split-by=timings

  #     - store_test_results:
  #         path: ~/rspec