parameters:
  answers:
    type: string
    default: 1\1
  os:
    type: executor
    default: ruby
executor: << parameters.os >>
working_directory: ~/sandbox

steps:
  - setup_remote_docker:
      docker_layer_caching: true
      version: 20.10.24
  - run:
      name: "Setup job environment variables"
      command: |
        echo 'export answers=<< parameters.answers>>' >> "$BASH_ENV"
        echo 'export app_name=artifact-${answers//\\/-}' >> "$BASH_ENV"
        echo 'export container=$(sudo docker ps -aqf "name=${app_name}")' >> "$BASH_ENV"
  - run: echo ${answers}    
  - run: echo ${app_name}    
  # - run: echo ${container}    
  # - run: sudo docker rm ${container}
  # - run: echo ${container}    
  - run: |
      sudo docker run \
        --name ${app_name} \
        -v ${PWD}:/${app_name} \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -u 0 \
        -it handsomefencer/roro:latest \
        sh -c "printf '<< parameters.answers >>\na\n' | roro rollon"
  - run: echo ${container}    
  - run: |
      sudo docker cp ${container}:/${app_name}/. ./
      sudo docker cp ${container}:/${app_name}/. .
      echo ${PWD}
      ls -a
      sudo docker-compose build 
      sudo docker-compose up -d
      
  #     container_id="$(sudo docker ps -aqf "name=${name}")"
  # - run: ls -a
  # - run: sudo docker-compose build
  # - run: sudo docker-compose build
  # - run: printenv
  # - run: echo ${PWD}