parameters:
  answers:
    type: string
    default: 1\1
  os:
    type: executor
    default: ruby
executor: << parameters.os >>
working_directory: ~/sandbox

steps:
  - setup_remote_docker:
      docker_layer_caching: true
      version: 19.03.12
  - run: |
      answers=<< parameters.answers >>
      name=artifact_${answers//\\/_}
      echo ${answers}
      echo ${name}
      sudo docker run \
        --name ${name} \
        -v ${PWD}:/${name} \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -u 0 \
        -it handsomefencer/roro:latest \
        sh -c "printf '<< parameters.answers >>\na\n' | roro rollon"

      container_id="$(sudo docker ps -aqf "name=${name}")"
      sudo docker cp ${container_id}:/${name}/. .
  - run: sudo docker-compose build 
  - run: sudo docker-compose up -d