parameters:
  answers:
    type: string
    default: 1\1
  os:
    type: executor
    default: ruby
executor: << parameters.os >>
working_directory: ~/sandbox

steps:
  - setup_remote_docker:
      docker_layer_caching: true
      version: 20.10.24
  - run:
      name: "Store answers and app_name variables"
      command: |
        answers=<< parameters.answers >>
        app_name="artifact-${answers//\\/-}"
        echo "export answers=${answers}" >> "$BASH_ENV"
        echo "export app_name='${app_name}'" >> "$BASH_ENV"
  - run: |
      sudo docker run \
        --name ${app_name} \
        -v ${PWD}:/${app_name} \
        -it handsomefencer/roro:latest \
        sh -c "printf '<< parameters.answers >>\na\n' | roro rollon"
  - run:
      name: "Store container id variable"
      command: |
        source $BASH_ENV
        container=$(sudo docker ps -aqf "name=${app_name}")
        echo "export container=${container}" >> "$BASH_ENV"
  
  - run: 
      name: 'Copy from container into sandbox'
      command: |
        cat $BASH_ENV
        source $BASH_ENV
        sudo docker cp ${container}:/${app_name}/. ./
        sudo docker-compose build 
        sudo docker-compose up -d

  # - run: 
        # echo ${container}
        # echo ${answers}
        # echo ${PWD}
        # ls -a
        # ls -a /home/circleci/sandbox/
        # sudo chown -R $USER:$USER . 
      


  #     container_id="$(sudo docker ps -aqf "name=${name}")"
  # - run: ls -a
  # - run: sudo docker-compose build
  # - run: sudo docker-compose build
  # - run: printenv
  # - run: echo ${PWD}