parameters:
  version:
    description: "version tag"
    default: "3.0"
    type: string
executor: docker-cimg-ruby
steps:
  - checkout
  - run: |
      bundle exec rake test TEST=test/roro/ci/*_test.rb