parameters:
  database:
    description: database
    default: postgres
    type: string
executor: machine-ubuntu
parallelism: 5
steps:
  - checkout
  - restore-and-save-cache
  - run:
      command: |
        export DEBUGGERER='true'
        circleci tests glob "test/roro/stacks/*/<< parameters.database >>/**/*_test.rb" | \
        circleci tests run \
        --command="xargs bundle exec rake test" \
        --split-by=timings