parameters:
  answers:
    type: string
    default: 1\1
  os:
    type: executor
    default: ruby
executor: << parameters.os >>
steps:
  - checkout
  - setup_remote_docker:
      docker_layer_caching: true
      version: 19.03.12
  - restore-and-save-cache
  - run: | 
      docker-compose build roro
      docker-compose run --rm roro \
      printf "<< parameters.answers >>\na\n" | roro rollon
  - run: sudo docker ps