parameters:
  version:
    description: "version tag"
    default: "3.0"
    type: string
docker:
  - image: ruby:<<parameters.version>>-alpine
steps:
  - checkout
  - run: |
      bundle exec rake test TEST=test/roro/ci/*_test.rb