parameters:
  version:
    description: "version tag"
    default: "3.0"
    type: string
docker:
  - image: cimg/ruby:<<parameters.version>>
steps:
  - checkout
  - run: bundle &&
  - run: bundle exec rake test TEST=test/roro/cli/*_test.rb