executor: machine-ubuntu
parallelism: 5
steps:
  - checkout
  - restore-and-save-cache
  - run:
      command: bundle exec rake test:stories
      when: always
  - store_test_results:
      path: test/reports
  # - run: |
  #     TEST=$(circleci tests glob "test/**/*/_test.rb" | circleci tests split)
  #     DEBUGGERER='true' bundle exec rake test $TEST
