environment: 
  - ANSWERS: "<< parameters.answers >>"
parameters:
  answers:
    type: string
    default: '2'
  os:
    type: executor
    default: docker-cimg-base
executor: << parameters.os >>


steps:
  - checkout
  - set-variables  
  - roro-image-build
  - artifact-generate
  - artifact-copy
  - artifact-up